-- Disable foreign key checks
SET FOREIGN_KEY_CHECKS = 0;

-- Modify data types in teams table
ALTER TABLE teams
MODIFY COLUMN team_id BIGINT NOT NULL AUTO_INCREMENT,
MODIFY COLUMN project_id BIGINT NOT NULL,
MODIFY COLUMN team_name VARCHAR(100) NOT NULL,
MODIFY COLUMN icon_name VARCHAR(50) NOT NULL,
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Modify data types in team_members table
ALTER TABLE team_members
MODIFY COLUMN team_id BIGINT NOT NULL,
MODIFY COLUMN user_id VARCHAR(100) NOT NULL,
MODIFY COLUMN joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Modify data types in projects table
ALTER TABLE projects
MODIFY COLUMN project_id BIGINT NOT NULL AUTO_INCREMENT,
MODIFY COLUMN project_name VARCHAR(100) NOT NULL,
MODIFY COLUMN description TEXT,
MODIFY COLUMN owner_id VARCHAR(100) NOT NULL,
MODIFY COLUMN due_date DATE,
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
MODIFY COLUMN background_image_url VARCHAR(255),
MODIFY COLUMN is_public BOOLEAN DEFAULT FALSE,
MODIFY COLUMN invite_token VARCHAR(255) UNIQUE;

-- project_members
ALTER TABLE project_members MODIFY COLUMN project_id BIGINT NOT NULL;

-- project_member_permissions
ALTER TABLE project_member_permissions MODIFY COLUMN project_id BIGINT NOT NULL;

-- categories
ALTER TABLE categories MODIFY COLUMN project_id BIGINT NOT NULL;

-- task_lists
ALTER TABLE task_lists MODIFY COLUMN category_id BIGINT NOT NULL;

-- list_entries
ALTER TABLE list_entries MODIFY COLUMN task_list_id BIGINT NOT NULL;
ALTER TABLE list_entries MODIFY COLUMN file_id BIGINT;

-- entry_team_assignments
ALTER TABLE entry_team_assignments MODIFY COLUMN team_id BIGINT NOT NULL;

--  bug_comments
ALTER TABLE bug_comments MODIFY COLUMN bug_id BIGINT NOT NULL;

--  bug_reports
ALTER TABLE bug_reports MODIFY COLUMN bug_id BIGINT AUTO_INCREMENT;

-- 
SET FOREIGN_KEY_CHECKS = 1; 